name: "cachix"
on: [push, pull_request]
jobs:
  tests:
    runs-on: [ubuntu-latest, macos-latest]
    steps:
    - uses: actions/checkout@v2.3.1
    - uses: cachix/install-nix-action@v10
    - uses: cachix/cachix-action@v6
      with:
        name: simonchatts
        signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
    - run: nix-build
    - run: nix-shell --run "echo OK"
