name: "CI checks"
on: [push, pull_request]
permissions:
  contents: read
jobs:
  # This is reduced to just clippy, since "nix flake check" in cachix.yml
  # actually does all the other CI checks.
  #
  # Clippy is done in a special way to use the additional features of
  # nightly, but without failing when those aren't available - see
  # https://github.com/actions-rs/meta/blob/master/recipes/nightly-lints.md
  clippy:
    name: clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - uses: actions-rs/toolchain@63eb9591781c46a70274cb3ebdf190fce92702e8 # v1
        with:
          profile: minimal
          toolchain: nightly
          override: true
          components: clippy
      - uses: actions-rs/cargo@e7f754b8e09f70ad8eb2c5aebf61e58e8403b210 # v1
        with:
          command: clippy
          args: -- -D warnings
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - uses: actions-rs/toolchain@63eb9591781c46a70274cb3ebdf190fce92702e8 # v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - uses: actions-rs/cargo@e7f754b8e09f70ad8eb2c5aebf61e58e8403b210 # v1
        with:
          command: test
